### ISSUE TITLE
Properly handle alpha channel

### ISSUE THREAD

**Issue by johnnyshields** [escpos/escpos-image#5]
Please see PR #4. The current code does NOT properly handle the alpha channel, it simply ignores it.

To see how this is wrong, consider the case of a pixel with rgba = 0,0,0,0. Because the current code ignores the alpha channel, this will be rendered as a BLACK pixel, but since alpha is 0, it should be WHITE (assuming white background.)

(Since nearly all thermal printers print on white paper, a white background is a reasonable assumption.)

Please re-read my code in PR #4 and hopefully implement according to my way or something similar.

**Comment by svoboda-jan** [comment]
Yes, as mentioned in #4 this is intentional until we figure out how to properly detect alpha on the image. `unless a == 255` doesn't seem to be right because that is a correct value for alpha.

I do agree with the white background assumption, but there should be an option to disable the blending in case it is not desired.

I can't address this issue now but if you have time, please feel free to research it and open a new PR.

**Comment by johnnyshields** [comment]
My previous PR (#4) already fixed this issue. We don't need an option to disable the alpha channel; the way I handle it works in 99.99% of actual use cases.

**Comment by johnnyshields** [comment]
I don't understand what you mean "until we figure out how to properly detect alpha on the image".

We already figured this out. `ChunkyPNG::Color#a` returns the alpha channel as an integer value between 0 (fully transparent) and 255 (fully opaque).

Refer to https://www.rubydoc.info/github/wvanbergen/chunky_png/ChunkyPNG%2FColor:a.

**Comment by svoboda-jan** [comment]
The condition is actually not necessary, it returns the same value for `alpha = 255`. I have added support for alpha and released a new version of the gem. To enable alpha composition pass the option `compose_alpha: true` to the constructor. (see example in the readme) By default white background is assumed, but this can be changed with the option `compose_alpha_bg` (255 by default).

**Comment by johnnyshields** [comment]
@svoboda-jan according to principle of least surprise, compose_alpha should be `true` by default. If I pass in a png image, I expect alpha to be evaluated (and I expect background to be white).

**Comment by svoboda-jan** [comment]
I have changed the default to `true` but only when mini_magick processing is not used. It is not the recommended usage. I have clarified it in the readme. The recommended usage (with `convert_to_monochrome`) yields best results and should be used if possible. It handles alpha, applies dithering and supports more formats.
