### ISSUE TITLE
Feedback on Refactor: Faster Minimagick rendering (possibly)

### ISSUE THREAD

**Issue by johnnyshields** [escpos/escpos-image#7]
Refactor on the whole looks good. For MiniMagick, rather than using `Escpos::Image#to_escpos` and calling ChunkyPng there, for faster performance you could actually output MiniMagick as a 1-bit-per-pixel bitmap (something like the code below) which skips all the RBG stuff and means bytes written/read as file I/O.

In other words I think `#to_escpos` belongs in the Processor class. There could be a base processor class that has the chunkypng implementation as a default, but for MiniMagick it could be overridden for speed.

```ruby
      MiniMagick::Tool::Convert.new do |i|
        i.size 576
        i.font 'Sans'
        i.pango "Test image"
        i.monochrome
        i.depth 1
        i.negate
        i << "test.png"
      end

      output, *_ = Open3.capture3("convert #{tmp_filename} -depth 1 R:-", binmode: true)
      output.chomp("\n")
```

**Comment by svoboda-jan** [comment]
Thanks for the feedback.

I think that `#to_escpos` does belong to the Image class, it is its core functionality: take image data and convert it to ESC/POS, but I do agree that this data could be provided by the processor, so there could be a method in each processor like `#pixels`.

Had the same idea of getting pixel data directly from MiniMagick, but not sure if it is worth. The way I wanted to do it is make MiniMagick output BMP after processiong, which is trivial to read.

**Comment by johnnyshields** [comment]
`#to_escpos` should be in the Image class but it should delegate to the processor, the same way `#chunky_png_image` method does.

The code I gave above which uses `depth 1` and `negate` (invert color) generates a 1-bit (monochrome) bitmap directly from Minimagick. I think the performance gain is worth it here.

**Comment by svoboda-jan** [comment]
Yes, I think processors should provide image data, but not implement `to_escpos` method as you wrote in the first post.

I have implemented the change and now MiniMagick processor provides pixel data, but using the official API, there is a `get_pixels` method on the image instance.

Another benefit is that ChunkyPng is now also an optional dependency, you can choose between the two processors and they are now both able to deliver pixel data to the `to_escpos` method alone.

Closing this issue, since it's now implemented, but we can continue the discussion here, if it's related. Any feedback is appreciated.

**Comment by johnnyshields** [comment]
hmmm I'm not sure the RGB stuff is needed in MiniMagick. Couldn't you just convert to monochrome there then work in 1-bit depth? I assume all ESC/POS printers have either black or white pixels, no grayscale or RGB...

**Comment by svoboda-jan** [comment]
Yes, I think they have. The reason I kept RGB stuff is that we don't know what options were applied to the image. Let's say that `grayscale` has been applied, in this case it applies a certain ratio to each component, which mimics the relative perceptual RGB color sensitivity of the human eye. In this case I want to take all the components and average them, and I'm not sure how monochrome handles this. Getting RBG is not that much of an overhead and public API is used, which should be preferred.

**Comment by svoboda-jan** [comment]
Also there are printers like Epson TM-U220 that have a secondary color, but not sure if that is supported in raster mode.
