### ISSUE TITLE
Escpos::Helpers methods don't work

### ISSUE THREAD

**Issue by TheJimmyX** [escpos/escpos-image#8]
Hi! 

NoMethodError (undefined method `big' for Escpos::Helpers:Module)

I got this error trying to do the basic usage wrote it in your guide

**Comment by svoboda-jan** [comment]
Hi,

could you please provide steps to reproduce the error?

**Comment by TheJimmyX** [comment]
Sure. 

1. In my Gemfile

gem 'escpos'
gem 'escpos-image'
gem 'mini_magick'

2. In my class HostSetting 
        def self.print_ticket
		@printer = Escpos::Printer.new
		@printer << "Some text"
		@printer << Escpos::Helpers.big("other text")
		system("echo #{@printer.to_escpos} > /dev/usb/lp1")
	end

3. When I call HostSetting.print_ticket I get this error:
NameError (uninitialized constant HostSetting::Helpers)

**Comment by svoboda-jan** [comment]
Thanks.

Aren't you perhaps missing a require? I tried to reproduce it and the following works:

```ruby
require "escpos"

class HostSetting
  def self.print_ticket
    @printer = Escpos::Printer.new
    @printer << "Some text"
    @printer << Escpos::Helpers.big("Other text")
    puts @printer.to_base64
  end
end

HostSetting.print_ticket
```

**Comment by TheJimmyX** [comment]
Hi! Thank you, but unfortunately did not work. 

`require "escpos"

class HostSetting < ApplicationRecord
	def self.print_ticket
		@printer = Escpos::Printer.new
		@printer << "Some text"
		@printer << Escpos::Helpers.big("other text")
		puts @printer.to_base64
	end
end`

**Comment by TheJimmyX** [comment]
What version of ruby should I use?

**Comment by svoboda-jan** [comment]
Ok, from the example you just posted I can see that you are probably calling it from a Rails application. Tested it again with rails and I can reproduce it. It seems to be an issue with bundler. If you don't need the `escpos-image` gem right now, it should work if you remove it from the Gemfile. I will look into this further.

**Comment by TheJimmyX** [comment]
Hi. Thank you so much for your support. Actually I need to use the escpos-image gem. However, I installed the gem with gem install escpos and got this error: 

`system': string contains null byte (ArgumentError)

I use a file .rb with code below. If I comment the line where helpers are called, it prints. 

require "escpos"
@printer = Escpos::Printer.new
@printer << "Some text"
@printer << Escpos::Helpers.big("other text")
puts @printer.to_base64
system("echo #{@printer.to_escpos} > /dev/usb/lp1")

**Comment by svoboda-jan** [comment]
In this case it is actually not a problem with the gem but probably has something to do with the content not being properly escaped. I would recommend the following to pass data to the printer:

```ruby
File.open("/dev/usb/lp1", "w") do |f|
  f.write @printer.to_escpos
end
```

**Comment by GuilhermeFontaniva** [comment]
Hey I'm having the same error, when I remove the image gem works, but how I'll use images then?

**Comment by nilsding** [comment]
The core issue here is that both gems provide a `escpos/helpers` file (see: [escpos](https://github.com/escpos/escpos/blob/8445515029ccaf1f3c104a9a95d693443dd82ae1/lib/escpos/helpers.rb), [escpos-images](https://github.com/escpos/escpos-image/blob/66f73800e917d8fa669885fd10b9552deb1720bc/lib/escpos/helpers.rb)), and this gets quite confusing when both gems are in Ruby's load path.  On my machine (using Bundler) the `escpos-image` gem is added to that load path before the `escpos` one, which means that the `helpers.rb` from `escpos-image` is loaded instead, therefore resulting in these `NoMethodError`s...

I found a way to work around this issue... it involves modifying Ruby's load path though.

First, append `require: false` to the escpos gems in the Gemfile:

```ruby
gem "escpos", "~> 0.0.10", require: false
gem "escpos-image", "~> 0.0.11", require: false
```

Then in an initialiser or wherever you need to use this library, require it:

```ruby
# remove the escpos-image gem from Ruby's LOAD_PATH
escpos_image_path = $LOAD_PATH.find { |p| p =~ /escpos-image/ }
$LOAD_PATH.delete(escpos_image_path)
# require the base escpos gem, which requires its own escpos/helpers
require 'escpos'
# re-add and require the escpos-image gem to Ruby's LOAD_PATH
$LOAD_PATH.insert($LOAD_PATH.index {|p| p =~ /escpos/}, escpos_image_path)
require 'escpos/image'
```

Only downside with that is that the helpers.rb from this gem will not be loaded, but that's a fine trade-off for my purposes...

The real fix would be to e.g. rename this gem's `lib/escpos` to `lib/escpos-image`, or perhaps move conflicting files to something like `lib/escpos/image/ext/helpers.rb` ...

**Comment by johnnyshields** [comment]
Fixed here https://github.com/escpos/escpos-image/pull/10.

**Comment by svoboda-jan** [comment]
Added in v. `0.0.12`.

**Comment by YupItsZac** [comment]
This seems to still be an issue. Does anyone have a recommendation for an alternative package to generate the ESC commands for images, while still using the other escpos package?
